// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewPlan() {
  return window['go']['controllers']['TrainingPlanController']['CreateNewPlan']();
}

export function DeletePlan(arg1) {
  return window['go']['controllers']['TrainingPlanController']['DeletePlan'](arg1);
}

export function GetAllPlans() {
  return window['go']['controllers']['TrainingPlanController']['GetAllPlans']();
}

export function SavePlan(arg1) {
  return window['go']['controllers']['TrainingPlanController']['SavePlan'](arg1);
}
