// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateNewPlan():Promise<models.TrainingPlan>;

export function DeletePlan(arg1:string):Promise<void>;

export function GetAllPlans():Promise<Array<models.TrainingPlan>>;

export function SavePlan(arg1:models.TrainingPlan):Promise<void>;
